spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

db:
  hostname: postgres
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db-name: ${POSTGRES_DB}
  db-type: postgres
  db-url: jdbc:postgresql://%s:%d/%s