spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  banner:
    location: classpath:/botcamp_api_banner.txt
  main:
    allow-circular-references: true
  application:
    name: Botcamp API

cors:
  allowed-headers:
    - "Content-Type"
    - "accept"
    - "Origin"
    - "Authorization"
  allowed-methods:
    - "GET"
    - "POST"
  allowed-origins:
    - "*"
  enabled: true
  pattern: "/**"


security:
  jwt:
    secret: botcampapilocal
    token-validity: 3
    unit: hours
  enabled: true


server:
  port: 7510

db:
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  hostname: localhost
  db-name: ${POSTGRES_DB}
  db-url: jdbc:h2:file:./db_data/botcamp;AUTO_SERVER=TRUE;MODE=PostgreSQL;
  db-type: h2
  port: ${PGPORT}

http-config:
  logging-enabled: true
  connection-timeout: 10
  socket-timeout: 10
  connection-timeout-unit: seconds
  socket-timeout-unit: minutes

botcamp:
  smtp:
    host: ${BOTCAMP_EMAIL_SENDER_HOST}
    port: ${BOTCAMP_EMAIL_SENDER_PORT}
    username: ${BOTCAMP_EMAIL_SENDER_USERNAME}
    password: ${BOTCAMP_EMAIL_SENDER_PASSWORD}
    start-tls-enabled: true
    ssl-protocols: TLSv1.2
    auth-enabled: true

swagger:
  title: Botcamp API
  description: Botcamp API
  version: 0.0.2
  contact:
      email: botcamp-api@hotmail.com
      name: Louis SANTUCCI
      url: https://github.com/louis-santucci/BotCamp

gmail-gateway:
  url: localhost
  protocol: http
  port: 7500
  credentials:
    username: ${BOTCAMP_USR1_USERNAME}
    password: ${BOTCAMP_USR1_PASSWORD}