-- YOU CAN INSERT YOUR USERS LIKE THE FOLLOWING:
INSERT INTO BOTCAMP_USER (USERNAME,PASSWORD,CREATED_AT,UPDATED_AT) VALUES ('botcamp','$2y$10$G8A7qjAnSSBLuTxR09Oia.RjSN49je2ZKeZUJn6P5/GE1BdAdeYCm',CURRENT_TIMESTAMP,null) ON CONFLICT DO NOTHING;
