-- YOU CAN INSERT YOUR USERS LIKE THE FOLLOWING:
INSERT INTO BOTCAMP_USER (ID,USERNAME,PASSWORD,AUTHORIZATIONS,CREATED_AT,UPDATED_AT) VALUES ('e193e175-c40d-442a-98ea-2ad7af7dd6b9','botcamp','$2y$10$YLakAx9tWaobR8J/gVYKFecS5sq3UkaAZvwuPGLe4K4EL34QsPLru','ADMIN',CURRENT_TIMESTAMP,null) ON CONFLICT DO NOTHING;

-- LOCK CONFIG FOR SCHEDULED TASKS
CREATE TABLE IF NOT EXISTS SHEDLOCK (
                          NAME varchar(64) NOT NULL,
                          LOCK_UNTIL timestamp NOT NULL,
                          LOCKED_AT timestamp NOT NULL,
                          LOCKED_BY varchar(255) NOT NULL,
                          PRIMARY KEY (NAME)
);


UPDATE EXECUTION SET STATUS='FAILURE' WHERE STATUS='RUNNING';