-- YOU CAN INSERT YOUR USERS LIKE THE FOLLOWING:
INSERT INTO BOTCAMP_USER (USERNAME,PASSWORD,GMAIL_EMAIL,CREATED_AT,UPDATED_AT) VALUES ('test','$2y$10$Pw7F3GnE5p/IrRRgsSkHguLW.UEyUJ/U1iZR/TVuPLc12cwbsoO5u','test',CURRENT_TIMESTAMP,null) ON CONFLICT DO NOTHING;
